// Provides a generic polymorphic MongoDB repository.
//
// SaveNew/Update methods accept any struct or pointer to a struut, and save it as a Mongo document in a given database/collection.
// Retrieval methods (GetById/GetAll) instantiate and populate the same struct type that was saved, by using reflection.
//
// The saved document has the following additional fields:
//
// - "_id" is the document identifier. By default it is the hex string representation of a new bson.ObjectId, but you may
// provide an IdGenerator to generate your own ID.
//
// - "_t" is a key that identifies the actual struct type that was passed. Since Go doesn't have a native mechanism
// for converting a type to/from a string, we use a custom naming scheme (provided by package typeregistry). For
// deserialization to work, the type must have been registered with typeregistry.Register().
//
// Internally, this package uses https://github.com/mitchellh/mapstructure to map to and from structures. As a consequence:
//
// * If you want to retrieve the "_id" field in your struct, you may use "mapstructure" tag to map it to any field of your
// struct, e.g.:
//          Id      string `mapstructure:"_id"`
// In this case it is advised that the field type matches the type generated by the IdGenerator, otherwise unexpected
// type conversions may occur.
//
// * If you want a sub-structure to be "flattened" (not nested) in the saved document, you may use the "squash" option
// of the "mapstructure" tag, e.g.:
//          EmbeddedStruct `mapstructure:",squash"`
//
package mgorepo
